"""
Mock API responses as per AlphaVantage spec.
"""

timeseries_response = {
            "Meta Data": {
                "1. Information": "Daily Prices (open, high, low, close) and Volumes",
                "2. Symbol": "IBM",
                "3. Last Refreshed": "2022-06-30",
                "4. Output Size": "Compact",
                "5. Time Zone": "US/Eastern"
            },
            "Time Series (Daily)": {
                "2022-06-30": {
                    "1. open": "139.5800",
                    "2. high": "142.4600",
                    "3. low": "139.2800",
                    "4. close": "141.1900",
                    "5. volume": "4878020"
                },
                "2022-06-29": {
                    "1. open": "142.7400",
                    "2. high": "143.5213",
                    "3. low": "139.5000",
                    "4. close": "140.7100",
                    "5. volume": "4161491"
                },
            },
        }

overview_response = {
    "Symbol": "IBM",
    "AssetType": "Common Stock",
    "Name": "International Business Machines",
    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company "
                   "headquartered in Armonk, New York, with operations in over 170 countries. The company began in "
                   "1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was "
                   "renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces "
                   "and sells computer hardware, middleware and software, and provides hosting and consulting "
                   "services in areas ranging from mainframe computers to nanotechnology. IBM is also a major "
                   "research organization, holding the record for most annual U.S. patents generated by a business ("
                   "as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine ("
                   "ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, "
                   "the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM "
                   "mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s "
                   "and 1970s.",
    "CIK": "51143",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "COMPUTER & OFFICE EQUIPMENT",
    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2022-03-31",
    "MarketCapitalization": "126551425000",
    "EBITDA": "12120001000",
    "PERatio": "23.19",
    "PEGRatio": "1.582",
    "BookValue": "21.18",
    "DividendPerShare": "6.57",
    "DividendYield": "0.0469",
    "EPS": "6.09",
    "RevenuePerShareTTM": "65.03",
    "ProfitMargin": "0.0946",
    "OperatingMarginTTM": "0.105",
    "ReturnOnAssetsTTM": "0.0271",
    "ReturnOnEquityTTM": "0.245",
    "RevenueTTM": "58361000000",
    "GrossProfitTTM": "31486000000",
    "DilutedEPSTTM": "6.09",
    "QuarterlyEarningsGrowthYOY": "-0.239",
    "QuarterlyRevenueGrowthYOY": "0.077",
    "AnalystTargetPrice": "143.63",
    "TrailingPE": "23.19",
    "ForwardPE": "14.45",
    "PriceToSalesRatioTTM": "2.168",
    "PriceToBookRatio": "6.74",
    "EVToRevenue": "3.007",
    "EVToEBITDA": "14.15",
    "Beta": "1.004",
    "52WeekHigh": "144.73",
    "52WeekLow": "111.84",
    "50DayMovingAverage": "136.66",
    "200DayMovingAverage": "130.24",
    "SharesOutstanding": "896320000",
    "DividendDate": "2022-06-10",
    "ExDividendDate": "2022-05-09"
}