"""migration step 2 - initial stock model

Revision ID: 1c191e652902
Revises: c74c157d9a6c
Create Date: 2022-07-01 11:11:07.695250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c191e652902'
down_revision = 'c74c157d9a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries', sa.JSON(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exchange', sa.String(length=8), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.Column('no_shares', sa.Integer(), nullable=True),
    sa.Column('trail_pe_ratio', sa.Float(), nullable=True),
    sa.Column('fwd_pe_ratio', sa.Float(), nullable=True),
    sa.Column('d_yield', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('low_52w', sa.Float(), nullable=True),
    sa.Column('eps', sa.JSON(), nullable=True),
    sa.Column('last_cache_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
